# Generated by Django 2.0.7 on 2018-07-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='at_risk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='earliest_dose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='protection',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='transmission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='schedule',
            field=models.TextField(),
        ),
    ]
