# Generated by Django 2.0.7 on 2018-07-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180709_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='incubation_period',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='disease',
            name='infectious_period',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='disease',
            name='vaccine_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
