# Generated by Django 2.0.7 on 2018-07-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180709_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='complications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='severity',
            field=models.TextField(blank=True),
        ),
    ]
