# Generated by Django 2.0.7 on 2018-07-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180709_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='mininum_interval',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
